db:
  image: ctsi/postgis
  ports:
   - "5432:5432"
  volumes_from:
   - volume
  privileged: true

volume:
  image: ctsi/postgis
  command: true
  volumes:
   - /var/lib/postgresql/data
  entrypoint: true
  privileged: true
