
app:
  image: redis
  ports:
   - "6379:6379"
  command: redis-server --appendonly yes
  volumes:
   - redis.conf:/usr/local/etc/redis/redis.conf
  volumes_from:
   - volume
  privileged: true


volume:
  image: redis
  command: true
  volumes:
   - /data
  privileged: true
