
httpd:
  image: nginx
  ports:
   - "80:80"
   - "443:443"
  external_links:
   - registry_webapp_1:registry
  volumes:
   - etc/cert:/etc/nginx/cert
   - etc/sites-enabled:/etc/nginx/sites-enabled
   - etc/conf.d:/etc/nginx/conf.d
   - etc/nginx.conf:/etc/nginx/nginx.conf
  privileged: true
