
app:
  image: ctsi/tomcat
  external_links:
   - postgresql_db_1:postgresql
  volumes:
   - supervisord.conf:/home/supervisord.conf
   - webapps:/home/tomcat/webapps
  environment:
   - TZ=Asia/Shanghai
   - JAVA_OPTS=-Xmx1024m
  privileged: true
