
app:
  image: ctsi/tomcat:8.0-jre8
  external_links:
   - postgresql_db_1:postgresql
  volumes:
   - webapps:/home/tomcat/webapps
  environment:
   - TZ=Asia/Shanghai
   - JAVA_OPTS=-Xmx1024m
  privileged: true
